name: Deploy to AWS Static Hosting
"on":
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
